<a href="https://colab.research.google.com/github/SrujanTopalle/deeplearninglab/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Develop a Python script to execute various learning rules commonly employed in
 deep learning, including the Hebbian Learning Rule, Perceptron Learning Rule, Delta
 Learning Rule, Correlation Learning Rule, and OutStar Learning Rule.

In [12]:
import numpy as np

In [13]:
def hebb(input_matrix,weight_matrix):
  return weight_matrix + np.outer(input_matrix,input_matrix)

In [14]:
def perceptron(input_matrix,weight_matrix,learning_rate,target_value):
  prediction = np.sign(np.dot(input_matrix,weight_matrix))
  error = target_value - prediction
  return weight_matrix + learning_rate * error * input_matrix

In [15]:
def delta(input_matrix,weight_matrix,learning_rate,target_value):
  prediction = np.dot(input_matrix,weight_matrix)
  error = prediction - target_value
  return weight_matrix + error * learning_rate * input_matrix

In [16]:
def correlation(input_matrix,weight_matrix):
  return weight_matrix + np.outer(input_matrix,input_matrix)

In [17]:
def outstar(input_matrix,weight_matrix,learning_rate):
  return weight_matrix + learning_rate * np.outer(input_matrix,input_matrix)

In [18]:
weight_matrix = np.random.rand(3,3)
input_matrix = np.random.rand(3)
target_value = 1
learning_rate = 0.1

In [21]:
print(f"Original weight matrix:\n\n{weight_matrix}")
print(f"Original input matrix:\n\n{input_matrix}")

Original weight matrix:

[[0.96342283 0.55602147 0.98150717]
 [0.49462727 0.63287503 0.86271995]
 [0.20079623 0.91962469 0.477521  ]]
Original input matrix:

[0.05294204 0.69452033 0.78551532]


In [22]:
print(f"Hebb:\n\n{hebb(input_matrix,weight_matrix)}")
print(f"Hebb:\n\n{perceptron(input_matrix,weight_matrix,learning_rate,target_value)}")
print(f"Delta:\n\n{delta(input_matrix,weight_matrix,learning_rate,target_value)}")
print(f"Correlation:\n\n{correlation(input_matrix,weight_matrix)}")
print(f"Outstar:\n\n{outstar(input_matrix,weight_matrix,learning_rate)}")

Hebb:

[[0.96622569 0.5927908  1.02309396]
 [0.53139659 1.11523352 1.40827631]
 [0.24238302 1.46518105 1.09455532]]
Hebb:

[[0.96342283 0.55602147 0.98150717]
 [0.49462727 0.63287503 0.86271995]
 [0.20079623 0.91962469 0.477521  ]]
Delta:

[[0.96105242 0.56931187 0.98356833]
 [0.49225686 0.64616543 0.86478111]
 [0.19842582 0.93291508 0.47958216]]
Correlation:

[[0.96622569 0.5927908  1.02309396]
 [0.53139659 1.11523352 1.40827631]
 [0.24238302 1.46518105 1.09455532]]
Outstar:

[[0.96370312 0.5596984  0.98566585]
 [0.4983042  0.68111088 0.91727558]
 [0.20495491 0.97418032 0.53922443]]
